version: '3'

vars:
  APP_NAME: pipeline-analyzer
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  BUILD_TIME:
    sh: date -u '+%Y-%m-%d_%H:%M:%S'

env:
  CGO_ENABLED: 0

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  deps:
    desc: ðŸ“¦ Install dependencies
    cmds:
      - echo "ðŸ“¦ Installing dependencies..."
      - go mod tidy
      - go mod download
      - go mod verify

  build:
    desc: ðŸ”¨ Build pipeline-analyzer
    cmds:
      - echo "ðŸ”¨ Building {{.APP_NAME}}..."
      - go build -ldflags "-X main.version={{.VERSION}} -X main.buildTime={{.BUILD_TIME}}" -o {{.APP_NAME}} ./cmd/{{.APP_NAME}}
    sources:
      - cmd/pipeline-analyzer/main.go
      - internal/**/*.go
      - go.mod
      - go.sum
    generates:
      - "{{.APP_NAME}}"

  install:
    desc: ðŸ“² Install pipeline-analyzer to /usr/local/bin
    deps: [build]
    cmds:
      - echo "ðŸ“² Installing {{.APP_NAME}}..."
      - sudo cp {{.APP_NAME}} /usr/local/bin/
      - echo "âœ… Installed {{.APP_NAME}} to /usr/local/bin"
      - echo "ðŸ’¡ Now you can run '{{.APP_NAME}}' from anywhere!"

  install-local:
    desc: ðŸ“² Install pipeline-analyzer to ~/bin (no sudo required)
    deps: [build]
    cmds:
      - mkdir -p ~/bin
      - cp {{.APP_NAME}} ~/bin/
      - echo "âœ… Installed {{.APP_NAME}} to ~/bin"
      - echo "ðŸ’¡ Make sure ~/bin is in your PATH"
      - echo "ðŸ’¡ Now you can run '{{.APP_NAME}}' from anywhere!"

  run:
    desc: ðŸš€ Run pipeline-analyzer with default config
    deps: [build]
    cmds:
      - echo "ðŸš€ Running {{.APP_NAME}}..."
      - ./{{.APP_NAME}} {{.CLI_ARGS}}

  run-help:
    desc: ðŸš€ Show pipeline-analyzer help
    deps: [build]
    cmds:
      - ./{{.APP_NAME}} --help

  run-version:
    desc: ðŸš€ Show pipeline-analyzer version
    deps: [build]
    cmds:
      - ./{{.APP_NAME}} --version

  clean:
    desc: ðŸ§¹ Clean up build artifacts
    cmds:
      - echo "ðŸ§¹ Cleaning up..."
      - rm -f {{.APP_NAME}}
      - rm -rf dist/
      - rm -rf .discovery/
      - rm -rf circleci-analysis/
      - go clean

  test:
    desc: ðŸ§ª Run tests
    cmds:
      - echo "ðŸ§ª Running tests..."
      - go test -v ./...

  test-coverage:
    desc: ðŸ§ª Run tests with coverage
    cmds:
      - echo "ðŸ§ª Running tests with coverage..."
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "ðŸ“Š Coverage report generated coverage.html"

  fmt:
    desc: ðŸŽ¯ Format code
    cmds:
      - echo "ðŸŽ¯ Formatting code..."
      - go fmt ./...
      - goimports -w . 2>/dev/null || true

  lint:
    desc: ðŸ” Lint code
    cmds:
      - echo "ðŸ” Linting code..."
      - golangci-lint run || echo "ðŸ’¡ Install golangci-lint for better linting"

  vet:
    desc: ðŸ” Vet code
    cmds:
      - echo "ðŸ” Vetting code..."
      - go vet ./...

  release:
    desc: ðŸ“¦ Build release versions for multiple platforms
    cmds:
      - echo "ðŸ“¦ Building release versions..."
      - mkdir -p dist
      - task: release-build
        vars:
          GOOS: darwin
          GOARCH: amd64
          SUFFIX: darwin-amd64
      - task: release-build
        vars:
          GOOS: darwin
          GOARCH: arm64
          SUFFIX: darwin-arm64
      - task: release-build
        vars:
          GOOS: linux
          GOARCH: amd64
          SUFFIX: linux-amd64
      - task: release-build
        vars:
          GOOS: linux
          GOARCH: arm64
          SUFFIX: linux-arm64
      - task: release-build
        vars:
          GOOS: windows
          GOARCH: amd64
          SUFFIX: windows-amd64
          EXT: .exe
      - echo "âœ… Release builds completed in dist/"
      - ls -la dist/

  release-build:
    internal: true
    cmds:
      - GOOS={{.GOOS}} GOARCH={{.GOARCH}} go build -ldflags "-X main.version={{.VERSION}} -X main.buildTime={{.BUILD_TIME}}" -o dist/{{.APP_NAME}}-{{.SUFFIX}}{{.EXT}} ./cmd/{{.APP_NAME}}

  check:
    desc: ðŸ”Ž Run all checks (fmt, vet, lint, test)
    cmds:
      - task: fmt
      - task: vet
      - task: lint
      - task: test

  setup:
    desc: ðŸ› ï¸ Initial setup for development
    cmds:
      - echo "ðŸ› ï¸ Setting up {{.APP_NAME}} development environment..."
      - task: deps
      - task: build
      - echo "âœ… Setup complete!"
      - echo "ðŸ’¡ Run 'task run' to analyze .circleci/config.yml"
      - echo "ðŸ’¡ Run 'task run-help' to see all options"
      - echo "ðŸ’¡ Run 'task install-local' to install globally"

  update:
    desc: ðŸ”„ Update dependencies
    cmds:
      - echo "ðŸ”„ Updating dependencies..."
      - go get -u ./...
      - go mod tidy
      - echo "âœ… Dependencies updated"

  demo:
    desc: ðŸŽ¬ Run demo with bash script reference
    deps: [build]
    cmds:
      - echo "ðŸŽ¬ Running demo analysis on bash script..."
      - echo "ðŸ“ Creating sample CircleCI config for demo..."
      - mkdir -p .demo/.circleci
      - |
        cat > .demo/.circleci/config.yml << 'EOF'
        version: 2.1
        
        jobs:
          build:
            docker:
              - image: cimg/go:1.21
            steps:
              - checkout
              - run: go mod download
              - run: go build -o app ./cmd/pipeline-analyzer
          
          test:
            docker:
              - image: cimg/go:1.21
            steps:
              - checkout
              - run: go mod download
              - run: go test ./...
          
          lint:
            docker:
              - image: golangci/golangci-lint:latest
            steps:
              - checkout
              - run: golangci-lint run
        
        workflows:
          main:
            jobs:
              - build
              - test:
                  requires: [build]
              - lint:
                  requires: [build]
        EOF
      - echo "ðŸš€ Running analysis..."
      - ./{{.APP_NAME}} --output-dir .demo/analysis .demo/.circleci/config.yml
      - echo "ðŸ“ Demo analysis complete! Check .demo/analysis/"
      - echo "ðŸ§¹ Cleaning up demo files..."
      - rm -rf .demo